version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    hostname: postgres
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

  school-service-api:
    stdin_open: true
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-api
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "${APP_PORT}:3000"
    restart: always
  
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    container_name: school-user-auth
    ports:
      - "${KEYCLOAK_PORT}:8080"
    env_file:
      - .env
    environment:
      KEYCLOAK_ADMIN: "${KEYCLOAK_ADMIN}"
      KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"
    command: start-dev

volumes:
  postgres-data:
  pgadmin-data:
